pipeline {
    agent any

    tools {
        nodejs 'NodeJS18' // Matches the tool name in your log
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/arunkumarmniloor-eng/k8s-Flask-Express-app.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                    # Go into the Express subfolder
                    cd Express
                    npm install
                '''
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                    cd Express
                    # Restart using pm2 (ensures sudo is set up for jenkins user)
                    sudo pm2 restart express-app || sudo pm2 start index.js --name express-app
                '''
            }
        }
    }

    post {
        success {
            echo 'Express deployment successful!'
        }
        failure {
            echo 'Express deploy failed!'
        }
    }
}
