pipeline {
    agent any

   stage('Checkout') {
    steps {
        git branch: 'main',
            url: 'https://github.com/arunkumarmniloor-eng/k8s-Flask-Express-app.git'
    }
}


        stage('Install Dependencies') {
            steps {
                sh '''
                    cd flask
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install -r requirements.txt
                '''
            }
        }

        stage('Test') {
            steps {
                sh '''
                    cd flask
                    . venv/bin/activate
                    python3 -m pytest tests/ --tb=short || true
                '''
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                    cd flask
                    # Start or restart using pm2
                    sudo pm2 restart flask-app || sudo pm2 start app.py --name flask-app
                '''
            }
        }
    }

    post {
        success {
            echo 'Flask deployment successful!'
        }
        failure {
            echo 'Flask deployment failed!'
        }
    }
}
